export enum Role{
  ADMIN = "ADMIN",
  ROOT = "ROOT",
  ENTERPRENER = "ENTERPRENER",
  CLIENT = "CLIENT",
  TRAINNER = "TRAINNER",
  LOANS = "LOANS",
  LOANS_STUDENT = "LOANS_STUDENT",
  LOANS_ENTERPRENER = "LOANS_ENTERPRENER",
  LOANS_INVESTOR = "LOANS_INVESTOR"
}
