export  enum Type{
  TUBERCULES= 'TUBERCULES',
  LEGUMES= 'LEGUMES',
  EPICES= 'EPICES',
  BOIS = 'BOIS',
  CEREALES = 'CEREALES',
  DERIVE_CEREALE = 'DERIVE DE CEREALE',
  FRUIT_ALIMENTAIRE = 'FRUIT ALIMENTAIRE',
  FRUIT_LEGUMES_CEREALE_AOP = 'FRUIT, LEGUME ET CEREALE AOP',
  HUILE_ESSENTIELLES = 'HUILE ESSENTIELLES',
  PLANTE_FIBRES = 'PLANTES A FIBRES',
  CUIR = 'CUIR',
}
